export const GetItems = () => {
  return [
    {
      id: 1,
      lote: 'LOTE-A',
      modelo: 'FIGO SEDAN',
      placa: 'ABC-123',
      cumplimiento: '100',
    },
    {
      id: 2,
      lote: 'LOTE-A',
      modelo: 'FIGO SEDAN',
      placa: 'XYZ-789',
      cumplimiento: '85',
    },
    {
      id: 3,
      lote: 'LOTE-A',
      modelo: 'FIGO HB',
      placa: 'LMN-456',
      cumplimiento: '90',
    },
    {
      id: 4,
      lote: 'LOTE-B',
      modelo: 'FIGO SUV',
      placa: 'GHI-012',
      cumplimiento: '60',
    },
    {
      id: 5,
      lote: 'LOTE-B',
      modelo: 'FIGO SUV',
      placa: 'JKL-345',
      cumplimiento: '100',
    },
    {
      id: 6,
      lote: 'LOTE-B',
      modelo: 'FIGO SEDAN',
      placa: 'MNO-678',
      cumplimiento: '75',
    },
    {
      id: 7,
      lote: 'LOTE-C',
      modelo: 'FIGO HB',
      placa: 'PQR-901',
      cumplimiento: '100',
    },
    {
      id: 8,
      lote: 'LOTE-C',
      modelo: 'FIGO HB',
      placa: 'STU-234',
      cumplimiento: '95',
    },
    {
      id: 9,
      lote: 'LOTE-C',
      modelo: 'FIGO SUV',
      placa: 'VWX-567',
      cumplimiento: '80',
    },
    {
      id: 10,
      lote: 'LOTE-D',
      modelo: 'FIGO SEDAN',
      placa: 'YZA-890',
      cumplimiento: '100',
    },
    {
      id: 11,
      lote: 'LOTE-D',
      modelo: 'FIGO SEDAN',
      placa: 'BCD-123',
      cumplimiento: '40',
    },
    {
      id: 12,
      lote: 'LOTE-D',
      modelo: 'FIGO HB',
      placa: 'EFG-456',
      cumplimiento: '100',
    },
    {
      id: 13,
      lote: 'LOTE-E',
      modelo: 'FIGO SUV',
      placa: 'HIJ-789',
      cumplimiento: '92',
    },
    {
      id: 14,
      lote: 'LOTE-E',
      modelo: 'FIGO SUV',
      placa: 'KLM-012',
      cumplimiento: '100',
    },
    {
      id: 15,
      lote: 'LOTE-E',
      modelo: 'FIGO SEDAN',
      placa: 'NOP-345',
      cumplimiento: '88',
    },
    {
      id: 16,
      lote: 'LOTE-F',
      modelo: 'FIGO HB',
      placa: 'QRS-678',
      cumplimiento: '100',
    },
    {
      id: 17,
      lote: 'LOTE-F',
      modelo: 'FIGO HB',
      placa: 'TUV-901',
      cumplimiento: '70',
    },
    {
      id: 18,
      lote: 'LOTE-F',
      modelo: 'FIGO SUV',
      placa: 'WXY-234',
      cumplimiento: '100',
    },
    {
      id: 19,
      lote: 'LOTE-G',
      modelo: 'FIGO SEDAN',
      placa: 'ZAB-567',
      cumplimiento: '98',
    },
    {
      id: 20,
      lote: 'LOTE-G',
      modelo: 'FIGO SEDAN',
      placa: 'CDE-890',
      cumplimiento: '50',
    },
  ];
};
