export const GetItems = () => {
  return [
    {
      idInspection: 1,
      lote: 'LOTE-A',
      model: 'FIGO SEDAN',
      plate: 'ABC-123',
      cumplimiento: '100',
      vin: '00001',
    },
    {
      idInspection: 2,
      lote: 'LOTE-A',
      model: 'FIGO SEDAN',
      plate: 'XYZ-789',
      cumplimiento: '85',
      vin: '00002',
    },
    {
      idInspection: 3,
      lote: 'LOTE-A',
      model: 'FIGO HB',
      plate: 'LMN-456',
      cumplimiento: '90',
      vin: '00003',
    },
    {
      idInspection: 4,
      lote: 'LOTE-B',
      model: 'FIGO SUV',
      plate: 'GHI-012',
      cumplimiento: '60',
      vin: '00004',
    },
    {
      idInspection: 5,
      lote: 'LOTE-B',
      model: 'FIGO SUV',
      plate: 'JKL-345',
      cumplimiento: '100',
      vin: '00005',
    },
    {
      idInspection: 6,
      lote: 'LOTE-B',
      model: 'FIGO SEDAN',
      plate: 'MNO-678',
      cumplimiento: '75',
      vin: '00006',
    },
    {
      idInspection: 7,
      lote: 'LOTE-C',
      model: 'FIGO HB',
      plate: 'PQR-901',
      cumplimiento: '100',
      vin: '00007',
    },
    {
      idInspection: 8,
      lote: 'LOTE-C',
      model: 'FIGO HB',
      plate: 'STU-234',
      cumplimiento: '95',
      vin: '00008',
    },
    {
      idInspection: 9,
      lote: 'LOTE-C',
      model: 'FIGO SUV',
      plate: 'VWX-567',
      cumplimiento: '80',
      vin: '00009',
    },
    {
      idInspection: 10,
      lote: 'LOTE-D',
      model: 'FIGO SEDAN',
      plate: 'YZA-890',
      cumplimiento: '100',
      vin: '00010',
    },
    {
      idInspection: 11,
      lote: 'LOTE-D',
      model: 'FIGO SEDAN',
      plate: 'BCD-123',
      cumplimiento: '40',
      vin: '00011',
    },
    {
      idInspection: 12,
      lote: 'LOTE-D',
      model: 'FIGO HB',
      plate: 'EFG-456',
      cumplimiento: '100',
      vin: '00012',
    },
    {
      idInspection: 13,
      lote: 'LOTE-E',
      model: 'FIGO SUV',
      plate: 'HIJ-789',
      cumplimiento: '92',
      vin: '00013',
    },
    {
      idInspection: 14,
      lote: 'LOTE-E',
      model: 'FIGO SUV',
      plate: 'KLM-012',
      cumplimiento: '100',
      vin: '00014',
    },
    {
      idInspection: 15,
      lote: 'LOTE-E',
      model: 'FIGO SEDAN',
      plate: 'NOP-345',
      cumplimiento: '88',
      vin: '00015',
    },
    {
      idInspection: 16,
      lote: 'LOTE-F',
      model: 'FIGO HB',
      plate: 'QRS-678',
      cumplimiento: '100',
      vin: '00016',
    },
    {
      idInspection: 17,
      lote: 'LOTE-F',
      model: 'FIGO HB',
      plate: 'TUV-901',
      cumplimiento: '70',
      vin: '00017',
    },
    {
      idInspection: 18,
      lote: 'LOTE-F',
      model: 'FIGO SUV',
      plate: 'WXY-234',
      cumplimiento: '100',
      vin: '00018',
    },
    {
      idInspection: 19,
      lote: 'LOTE-G',
      model: 'FIGO SEDAN',
      plate: 'ZAB-567',
      cumplimiento: '98',
      vin: '00019',
    },
    {
      idInspection: 20,
      lote: 'LOTE-G',
      model: 'FIGO SEDAN',
      plate: 'CDE-890',
      cumplimiento: '50',
      vin: '00020',
    },
  ];
};
